# Generated by Django 5.0.6 on 2024-07-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.TextField(default='No details'),
        ),
    ]
